import * as fs from 'fs'
import yaml from 'yaml'
import simpleWorkflow from '~/examples/simple-workflow'

import { Paths, format } from './util'

const workflowFile = new yaml.Document(simpleWorkflow)
workflowFile.commentBefore = [
  'This is an autogenerated file!',
  'Do not edit it directly!',
  'Instead, edit the typescript file located at: _path_!',
]
  .map(line => ` ${line}`)
  .join('\n')

fs.writeFileSync(
  Paths.root('.github/workflows/simple-workflow.yml'),
  format(String(workflowFile), 'yaml'),
  'utf-8',
)
