import * as fs from 'fs'
import * as path from 'path'
import yaml from 'yaml'

import { Paths, format } from './util'

const getWorkflow = async () => {
  const WORKFLOW_FILE = process.env.WORKFLOW_FILE
  if (typeof WORKFLOW_FILE !== 'string') {
    throw new Error('environment variable "WORKFLOW_DIR" must be set')
  }

  return [WORKFLOW_FILE, (await import(WORKFLOW_FILE)).default] as const
}

const toFilePath = (templatePath: string) => {
  const parts = path.basename(templatePath).split('.')
  parts.pop()

  return Paths.root(`.github/workflows/${parts.join('.')}.yml`)
}

const main = async () => {
  const [templatePath, definition] = await getWorkflow()

  const workflowFile = new yaml.Document(definition)
  workflowFile.commentBefore = [
    'This is an autogenerated file!',
    'Do not edit it directly!',
    `Instead, edit the typescript file located at: ${templatePath}!`,
  ]
    .map(line => ` ${line}`)
    .join('\n')

  fs.writeFileSync(
    toFilePath(templatePath),
    format(String(workflowFile), 'yaml'),
    'utf-8',
  )
}

main()
