import fs from 'fs'
import path from 'path'
import { dump as toYaml } from 'js-yaml'
import { Workflow } from './models/github'

const toComments = (lines: string[]) => lines.map(line => `# ${line}`).join('\n')

export const DEFAULT_COMMENTS = [
  '🚨 THIS IS A GENERATED FILE 🚨',
  '🙅‍♀️ DO NOT EDIT THIS FILE DIRECTLY 🙅‍♂️',
]

type Options = {
  comments?: string[]
}

const toWorkflowYaml = (workflow: Workflow, options?: Options): string =>
  [toComments(options?.comments ?? DEFAULT_COMMENTS), toYaml(workflow)]
    .filter(Boolean)
    .join('\n\n')

export default toWorkflowYaml
